# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# See https://jekyllrb.com/docs/configuration/ for docs

# Site settings, accessible through {{ site.<variable> }}
title: The website of Joshua Nelson
email: jyn514@gmail.com
author: Joshua Nelson
description: >- # this means to ignore newlines until "baseurl:"
    This is my personal website, which I made over break on a whim.
    I hope you enjoy!
baseurl: ""
resume: Resume.pdf
github_username:  jyn514
keybase_username: jyn514
linkedin_username:  joshuayn
public_key: E655823D8D8B1088
timezone: America/New_York

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Joshua Nelson"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - scripts

include:
    - .well-known
